### ISSUE TITLE
Updating to 2.2.703 results in MODULE_NOT_FOUND on common-utils

### ISSUE THREAD

**Issue by glennsc** [Authress-Engineering/openapi-explorer#248]
I'm that guy embedding openapi-explorer in Vitepress.  The "build" step is simply `Vitepress build.`

All has been well:  `bun run docs:build` works on `openapi-explorer@2.2.702`.

Installing latest explorer 2.2.703 and the `build` command errors with:

> Error [ERR_MODULE_NOT_FOUND]: Cannot find module <mypath>/node_modules/openapi-explorer/dist/es/utils/common-utils' imported from <mypath>node_modules/openapi-explorer/dist/es/templates/security-scheme-template.js

**Comment by wparad** [comment]
Well that's definitely unexpected, it's possible something was missed. We'll try to see if it is reproducible and then go from there.

**Comment by wparad** [comment]
Should be good now in the latest version of the library. Thanks for reporting this.
